global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'slurm_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['slurm_exporter:8080']
